/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* LidarUart_SCB_IRQ */
    const cy_stc_sysint_t LidarUart_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)LidarUart_SCB_IRQ__INTC_NUMBER,
        .intrPriority = LidarUart_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* ExternalUart_SCB_IRQ */
    const cy_stc_sysint_t ExternalUart_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)ExternalUart_SCB_IRQ__INTC_NUMBER,
        .intrPriority = ExternalUart_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* OneMsInterrupt */
    const cy_stc_sysint_t OneMsInterrupt_cfg = {
        .intrSrc = (IRQn_Type)OneMsInterrupt__INTC_NUMBER,
        .intrPriority = OneMsInterrupt__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

