/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* DcMotorSpeed */
#define DcMotorSpeed_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define DcMotorSpeed_0_INBUF_ENABLED 0u
#define DcMotorSpeed_0_INIT_DRIVESTATE 1u
#define DcMotorSpeed_0_INIT_MUXSEL 8u
#define DcMotorSpeed_0_INPUT_SYNC 2u
#define DcMotorSpeed_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DcMotorSpeed_0_NUM 0u
#define DcMotorSpeed_0_PORT GPIO_PRT9
#define DcMotorSpeed_0_SLEWRATE CY_GPIO_SLEW_FAST
#define DcMotorSpeed_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define DcMotorSpeed_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define DcMotorSpeed_INBUF_ENABLED 0u
#define DcMotorSpeed_INIT_DRIVESTATE 1u
#define DcMotorSpeed_INIT_MUXSEL 8u
#define DcMotorSpeed_INPUT_SYNC 2u
#define DcMotorSpeed_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DcMotorSpeed_NUM 0u
#define DcMotorSpeed_PORT GPIO_PRT9
#define DcMotorSpeed_SLEWRATE CY_GPIO_SLEW_FAST
#define DcMotorSpeed_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LidarUart_rx */
#define LidarUart_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define LidarUart_rx_0_INBUF_ENABLED 1u
#define LidarUart_rx_0_INIT_DRIVESTATE 1u
#define LidarUart_rx_0_INIT_MUXSEL 18u
#define LidarUart_rx_0_INPUT_SYNC 2u
#define LidarUart_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LidarUart_rx_0_NUM 0u
#define LidarUart_rx_0_PORT GPIO_PRT8
#define LidarUart_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LidarUart_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LidarUart_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define LidarUart_rx_INBUF_ENABLED 1u
#define LidarUart_rx_INIT_DRIVESTATE 1u
#define LidarUart_rx_INIT_MUXSEL 18u
#define LidarUart_rx_INPUT_SYNC 2u
#define LidarUart_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LidarUart_rx_NUM 0u
#define LidarUart_rx_PORT GPIO_PRT8
#define LidarUart_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define LidarUart_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LidarUart_tx */
#define LidarUart_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LidarUart_tx_0_INBUF_ENABLED 0u
#define LidarUart_tx_0_INIT_DRIVESTATE 1u
#define LidarUart_tx_0_INIT_MUXSEL 18u
#define LidarUart_tx_0_INPUT_SYNC 2u
#define LidarUart_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LidarUart_tx_0_NUM 1u
#define LidarUart_tx_0_PORT GPIO_PRT8
#define LidarUart_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LidarUart_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LidarUart_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LidarUart_tx_INBUF_ENABLED 0u
#define LidarUart_tx_INIT_DRIVESTATE 1u
#define LidarUart_tx_INIT_MUXSEL 18u
#define LidarUart_tx_INPUT_SYNC 2u
#define LidarUart_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LidarUart_tx_NUM 1u
#define LidarUart_tx_PORT GPIO_PRT8
#define LidarUart_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define LidarUart_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* DirectionInput1 */
#define DirectionInput1_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define DirectionInput1_0_INBUF_ENABLED 0u
#define DirectionInput1_0_INIT_DRIVESTATE 0u
#define DirectionInput1_0_INIT_MUXSEL 0u
#define DirectionInput1_0_INPUT_SYNC 2u
#define DirectionInput1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DirectionInput1_0_NUM 1u
#define DirectionInput1_0_PORT GPIO_PRT9
#define DirectionInput1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define DirectionInput1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define DirectionInput1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define DirectionInput1_INBUF_ENABLED 0u
#define DirectionInput1_INIT_DRIVESTATE 0u
#define DirectionInput1_INIT_MUXSEL 0u
#define DirectionInput1_INPUT_SYNC 2u
#define DirectionInput1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DirectionInput1_NUM 1u
#define DirectionInput1_PORT GPIO_PRT9
#define DirectionInput1_SLEWRATE CY_GPIO_SLEW_FAST
#define DirectionInput1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* DirectionInput2 */
#define DirectionInput2_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define DirectionInput2_0_INBUF_ENABLED 0u
#define DirectionInput2_0_INIT_DRIVESTATE 0u
#define DirectionInput2_0_INIT_MUXSEL 0u
#define DirectionInput2_0_INPUT_SYNC 2u
#define DirectionInput2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DirectionInput2_0_NUM 2u
#define DirectionInput2_0_PORT GPIO_PRT9
#define DirectionInput2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define DirectionInput2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define DirectionInput2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define DirectionInput2_INBUF_ENABLED 0u
#define DirectionInput2_INIT_DRIVESTATE 0u
#define DirectionInput2_INIT_MUXSEL 0u
#define DirectionInput2_INPUT_SYNC 2u
#define DirectionInput2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DirectionInput2_NUM 2u
#define DirectionInput2_PORT GPIO_PRT9
#define DirectionInput2_SLEWRATE CY_GPIO_SLEW_FAST
#define DirectionInput2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* ExternalUart_rx */
#define ExternalUart_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define ExternalUart_rx_0_INBUF_ENABLED 1u
#define ExternalUart_rx_0_INIT_DRIVESTATE 1u
#define ExternalUart_rx_0_INIT_MUXSEL 18u
#define ExternalUart_rx_0_INPUT_SYNC 2u
#define ExternalUart_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ExternalUart_rx_0_NUM 0u
#define ExternalUart_rx_0_PORT GPIO_PRT5
#define ExternalUart_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define ExternalUart_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define ExternalUart_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define ExternalUart_rx_INBUF_ENABLED 1u
#define ExternalUart_rx_INIT_DRIVESTATE 1u
#define ExternalUart_rx_INIT_MUXSEL 18u
#define ExternalUart_rx_INPUT_SYNC 2u
#define ExternalUart_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ExternalUart_rx_NUM 0u
#define ExternalUart_rx_PORT GPIO_PRT5
#define ExternalUart_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define ExternalUart_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* ExternalUart_tx */
#define ExternalUart_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define ExternalUart_tx_0_INBUF_ENABLED 0u
#define ExternalUart_tx_0_INIT_DRIVESTATE 1u
#define ExternalUart_tx_0_INIT_MUXSEL 18u
#define ExternalUart_tx_0_INPUT_SYNC 2u
#define ExternalUart_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ExternalUart_tx_0_NUM 1u
#define ExternalUart_tx_0_PORT GPIO_PRT5
#define ExternalUart_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define ExternalUart_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define ExternalUart_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define ExternalUart_tx_INBUF_ENABLED 0u
#define ExternalUart_tx_INIT_DRIVESTATE 1u
#define ExternalUart_tx_INIT_MUXSEL 18u
#define ExternalUart_tx_INPUT_SYNC 2u
#define ExternalUart_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ExternalUart_tx_NUM 1u
#define ExternalUart_tx_PORT GPIO_PRT5
#define ExternalUart_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define ExternalUart_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LidarMotorSpeed */
#define LidarMotorSpeed_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LidarMotorSpeed_0_INBUF_ENABLED 0u
#define LidarMotorSpeed_0_INIT_DRIVESTATE 1u
#define LidarMotorSpeed_0_INIT_MUXSEL 8u
#define LidarMotorSpeed_0_INPUT_SYNC 2u
#define LidarMotorSpeed_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LidarMotorSpeed_0_NUM 6u
#define LidarMotorSpeed_0_PORT GPIO_PRT10
#define LidarMotorSpeed_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LidarMotorSpeed_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LidarMotorSpeed_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LidarMotorSpeed_INBUF_ENABLED 0u
#define LidarMotorSpeed_INIT_DRIVESTATE 1u
#define LidarMotorSpeed_INIT_MUXSEL 8u
#define LidarMotorSpeed_INPUT_SYNC 2u
#define LidarMotorSpeed_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LidarMotorSpeed_NUM 6u
#define LidarMotorSpeed_PORT GPIO_PRT10
#define LidarMotorSpeed_SLEWRATE CY_GPIO_SLEW_FAST
#define LidarMotorSpeed_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* ServoPositionControl */
#define ServoPositionControl_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define ServoPositionControl_0_INBUF_ENABLED 0u
#define ServoPositionControl_0_INIT_DRIVESTATE 1u
#define ServoPositionControl_0_INIT_MUXSEL 8u
#define ServoPositionControl_0_INPUT_SYNC 2u
#define ServoPositionControl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ServoPositionControl_0_NUM 0u
#define ServoPositionControl_0_PORT GPIO_PRT10
#define ServoPositionControl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define ServoPositionControl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define ServoPositionControl_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define ServoPositionControl_INBUF_ENABLED 0u
#define ServoPositionControl_INIT_DRIVESTATE 1u
#define ServoPositionControl_INIT_MUXSEL 8u
#define ServoPositionControl_INPUT_SYNC 2u
#define ServoPositionControl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define ServoPositionControl_NUM 0u
#define ServoPositionControl_PORT GPIO_PRT10
#define ServoPositionControl_SLEWRATE CY_GPIO_SLEW_FAST
#define ServoPositionControl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
